CREATE TABLE Freq_Item (
	userID 	INTEGER NOT NULL,
	NDB_NO	INTEGER NOT NULL, 
	count	INTEGER NOT NULL, 
	FOREIGN KEY (NDB_NO) REFERENCES mytable (NDB_NO),
	FOREIGN KEY (userID) REFERENCES User_Info (userID)
);

INSERT INTO Freq_Item(userID, NDB_NO, count) VALUES (1, 2001, 1);